- hosts: jenkins
  pre_tasks:
    - name: Verify Ansible meets jenkins_plugin version requirements.
      assert:
        that: "ansible_version.full is version_compare('2.10', '>=')"
        msg: "You must update Ansible to at least 2.10 to use this cookbook"
  become: true

  tasks:
    - name: Waiting for Jenkins to start
      wait_for:
        port: 8080

    - name: Initiate the fact
      set_fact:
        jenkins_restart_required: no

    - name: Installing Jenkins Plugins
      jenkins_plugin:
        name: "{{item}}"
        url_username: admin
        url_password: "{{lookup('file', 'jenkins_password.txt')}}" # you have to add this file yourself
        timeout: 300

      register: jenkins_plugin_result
      with_items:
        - ssh-slaves
        - cloudbees-folder        # allows us to have folders
        - rebuild                 # nice rebuild button to rerun a job with the same parameters
        - console-badge           # magic button to see the console
        - build-name-setter       # allow builds to change their names
        - build-timestamp         # show timestamps
        - build-with-parameters   # allows (github) hooks to trigger builds
        - build-user-vars-plugin  # allow jenkinsfiles to get the current jenkins user
        - build-token-root        # allows github to trigger builds even when an anonymous user has no read permission
        - workflow-aggregator     # jenkins pipeline
        - antisamy-markup-formatter # HTML descriptions
        - configuration-as-code
        - extensible-choice-parameter # text box with pre defined values as suggestions
        - git

        # needed when one has real users
        # - matrix-auth
        # - pam-auth
        # - ldap
        # - role-strategy
        # - active-directory


    - name: Restart Jenkins if required
      service:
        name: jenkins
        state: restarted
      when: jenkins_plugin_result.changed

    - name: Copy Jenkins Config as Code Settings to Server
      copy:
        src: jenkins_as_a_code_settings.yaml
        dest: /var/lib/jenkins/jenkins.yaml
      register: jenkins_as_code_settigns_result

    - name: "wait for Jenkins to finish restarting to come up"
      uri:
        url: "http://127.0.0.1:8080/"
        status_code: 403
      register: result
      until: result.status == 403 or result.status == 200
      retries: 60
      delay: 3
      when: jenkins_as_code_settigns_result.changed

    - name: Load Jenkins Config as Code Settings
      jenkins_script:
        script: "{{lookup('file', 'files/reload.groovy')}}"
        user: admin
        password: "{{lookup('file', 'jenkins_password.txt')}}" # you have to add this file yourself
      when: jenkins_as_code_settigns_result.changed

